on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy_vite:
    name: Deploy Vite Project
    runs-on: ubuntu-latest
    
    steps:
    - name: Set Up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Pull Changes from Repository
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        cd ${{ secrets.WORK_DIR }}
        git checkout ${{ secrets.MAIN_BRANCH }}
        git pull
        EOF

    - name: Install Dependencies
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        cd ${{ secrets.WORK_DIR }}
        npm install
        EOF

    - name: Build Vite Project
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        cd ${{ secrets.WORK_DIR }}
        npm run build
        EOF

    - name: Deploy Built Files
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
        cd ${{ secrets.WORK_DIR }}
        rm -rf ${{ secrets.DEPLOY_DIR }}/*
        cp -r dist/* ${{ secrets.DEPLOY_DIR }}/
        EOF

    - name: Cleanup
      run: |
        rm -rf ~/.ssh
