on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_vite:
    name: Deploy Vite Project
    runs-on: ubuntu-latest

    steps:
    - name: Set Up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Configure SSH
      run: |
        echo -e "Host ${secrets.SSH_HOST}\n\
        User ${secrets.SSH_USER}\n\
        IdentityFile ~/.ssh/id_rsa\n\
        StrictHostKeyChecking no" > ~/.ssh/config

    - name: Debug SSH Connection
      run: ssh -vvv ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"

    - name: Pull Changes from Repository
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"
