on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_vite:
    name: Deploy Vite Project
    runs-on: ubuntu-latest

    steps:
    - name: Set Up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Configure SSH
      run: |
        echo -e "Host ${SSH_HOST}\n\
        User ${SSH_USER}\n\
        IdentityFile ~/.ssh/id_rsa\n\
        StrictHostKeyChecking no" > ~/.ssh/config
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}

    - name: Pull Changes from Repository
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && npm i && npm run build && service nginx restart"